### ISSUE TITLE
Fails to work unless it is initial view controller

### ISSUE THREAD

**Issue by zeroskill** [pixyzehn/MediumMenu#12]
Tried using this library in a project where this nav controller takes over after a segue from another UIViewController. The menu still slides down as expected, but none of the menu items are clickable.

**Comment by pixyzehn** [comment]
See version 1.1.3
You can set the `enabled` as a property.
If you don't want to use menu any more, you are able to turn the menu off.

**Comment by zeroskill** [comment]
Still doesn't fix the issue, but I'm thinking this is more of a rootViewController/navigation-stack issue.

**Comment by pixyzehn** [comment]
I see. Thanks for letting me know.

**Comment by VeveCorp** [comment]
Was this issue ever fixed?

**Comment by dilizarov** [comment]
+1. This only works if it is on the initial view controller, but if you have a login view controller or something that segues into a UINavigationController with this, then it breaks. Otherwise, its a pretty nice library.

**Comment by MaeseppTarvo** [comment]
+1 .. If you logout and then login, menu items are unresponsive.

**Comment by Amaneo** [comment]
so this could never be fixed ?

**Comment by MaeseppTarvo** [comment]
I checked it out also and it seems that the problem is that if you "logout" and set your initial viewcontroller to your welcome view and "log in" again. It keeps the previous menu underneath.

You can check out the following images:

1. This is in normal phase

<img width="554" alt="normal1" src="https://cloud.githubusercontent.com/assets/8416295/24580640/0fdd824a-1714-11e7-9a8a-a9be1e94b7d5.png">


2. This is after logout and back login

<img width="779" alt="bad" src="https://cloud.githubusercontent.com/assets/8416295/24580643/1995c356-1714-11e7-9a16-e567dfab4f87.png">
